<script lang="ts">
  // IconDisplay.svelte
  import Icon from '@iconify/svelte';

  // Props using Svelte 5 runes syntax
  interface Props {
    emoji?: string;
    className?: string;
  }

  let { emoji, className = 'w-5 h-5' }: Props = $props();

  // Comprehensive Functional Emoji to Iconify Mapping
  const EMOJI_TO_ICONIFY: Record<string, string> = {
    // Navigation & Arrows
    "🏠": "heroicons:home",
    "🏡": "heroicons:home-modern",
    "⬆️": "heroicons:arrow-up",
    "⬇️": "heroicons:arrow-down",
    "⬅️": "heroicons:arrow-left",
    "➡️": "heroicons:arrow-right",
    "↗️": "heroicons:arrow-up-right",
    "↘️": "heroicons:arrow-down-right",
    "↙️": "heroicons:arrow-down-left",
    "↖️": "heroicons:arrow-up-left",
    "↕️": "heroicons:arrows-up-down",
    "↔️": "heroicons:arrows-right-left",
    "🔙": "heroicons:arrow-left",
    "🔜": "heroicons:arrow-right",
    "🔝": "heroicons:arrow-up",
    "↩️": "heroicons:arrow-uturn-left",
    "↪️": "heroicons:arrow-uturn-right",
    "⤴️": "heroicons:arrow-trending-up",
    "⤵️": "heroicons:arrow-trending-down",
    "🔄": "heroicons:arrow-path",

    // Communication
    "📧": "heroicons:envelope",
    "📨": "heroicons:envelope-open",
    "📞": "heroicons:phone",
    "📱": "heroicons:device-phone-mobile",
    "💬": "heroicons:chat-bubble-left",
    "💭": "heroicons:chat-bubble-oval-left",
    "🗨️": "heroicons:chat-bubble-left-ellipsis",
    "📢": "heroicons:megaphone",
    "📣": "heroicons:speaker-wave",
    "📲": "heroicons:device-phone-mobile",
    "☎️": "heroicons:phone",

    // UI Controls
    "✅": "heroicons:check",
    "❌": "heroicons:x-mark",
    "❎": "heroicons:x-circle",
    "✔️": "heroicons:check-circle",
    "⭐": "heroicons:star",
    "🔍": "heroicons:magnifying-glass",
    "🔎": "heroicons:magnifying-glass-plus",
    "🔒": "heroicons:lock-closed",
    "🔓": "heroicons:lock-open",
    "🔑": "heroicons:key",
    "⚙️": "heroicons:cog-6-tooth",
    "🛠️": "heroicons:wrench-screwdriver",
    "🔧": "heroicons:wrench",
    "⛔": "heroicons:no-symbol",
    "🚫": "heroicons:no-symbol",
    "❗": "heroicons:exclamation-circle",
    "⚠️": "heroicons:exclamation-triangle",
    "ℹ️": "heroicons:information-circle",
    "❓": "heroicons:question-mark-circle",
    "➕": "heroicons:plus",
    "➖": "heroicons:minus",
    "✖️": "heroicons:x-mark",

    // Files & Documents
    "📁": "heroicons:folder",
    "📂": "heroicons:folder-open",
    "📄": "heroicons:document",
    "📃": "heroicons:document-text",
    "📋": "heroicons:clipboard",
    "📊": "heroicons:chart-bar",
    "📈": "heroicons:chart-bar",
    "📉": "heroicons:presentation-chart-line",
    "🗂️": "heroicons:folder",
    "🗃️": "heroicons:archive-box",
    "🗄️": "heroicons:archive-box",
    "📑": "heroicons:document-duplicate",
    "📜": "heroicons:document",
    "📰": "heroicons:newspaper",
    "📓": "heroicons:book-open",
    "📔": "heroicons:book-open",
    "📕": "heroicons:book-open",
    "📗": "heroicons:book-open",
    "📘": "heroicons:book-open",
    "📙": "heroicons:book-open",
    "📚": "heroicons:book-open",

    // Office & Business
    "💼": "heroicons:briefcase",
    "🏢": "heroicons:building-office",
    "🏪": "heroicons:building-storefront",
    "🏦": "heroicons:building-library",
    "💻": "heroicons:computer-desktop",
    "🖥️": "heroicons:computer-desktop",
    "🖨️": "heroicons:printer",
    "💳": "heroicons:credit-card",
    "💰": "heroicons:banknotes",
    "💵": "heroicons:currency-dollar",
    "💴": "heroicons:currency-yen",
    "💶": "heroicons:currency-euro",
    "💷": "heroicons:currency-pound",
    "🗓️": "heroicons:calendar",
    "📅": "heroicons:calendar-days",
    "📆": "heroicons:calendar-days",

    // Media & Entertainment
    "▶️": "heroicons:play",
    "⏸️": "heroicons:pause",
    "⏹️": "heroicons:stop",
    "⏭️": "heroicons:forward",
    "⏮️": "heroicons:backward",
    "⏯️": "heroicons:play-pause",
    "🔊": "heroicons:speaker-wave",
    "🔇": "heroicons:speaker-x-mark",
    "📷": "heroicons:camera",
    "🎥": "heroicons:video-camera",
    "🎬": "heroicons:film",
    "🎵": "heroicons:musical-note",
    "🎶": "heroicons:musical-note",
    "📺": "heroicons:tv",
    "📻": "heroicons:radio",

    // Technology & Computing
    "⌨️": "material-symbols:keyboard",
    "🖱️": "material-symbols:mouse",
    "💾": "material-symbols:save",
    "💿": "material-symbols:album",
    "📀": "material-symbols:album",
    "💽": "material-symbols:album",
    "🔌": "material-symbols:power",
    "🔋": "heroicons:battery-100",
    "📠": "material-symbols:fax",

    // Transportation
    "🚗": "heroicons:truck",
    "🚕": "heroicons:truck",
    "🚙": "heroicons:truck",
    "🚌": "heroicons:truck",
    "🚎": "heroicons:truck",
    "🏎️": "heroicons:truck",
    "🚓": "heroicons:truck",
    "🚑": "heroicons:truck",
    "🚒": "heroicons:truck",
    "🚐": "heroicons:truck",
    "🛻": "heroicons:truck",
    "🚚": "heroicons:truck",
    "🚛": "heroicons:truck",
    "🚜": "heroicons:truck",
    "🛴": "material-symbols:directions-bike",
    "🚲": "material-symbols:directions-bike",
    "🛵": "material-symbols:two-wheeler",
    "🏍️": "material-symbols:two-wheeler",
    "✈️": "heroicons:paper-airplane",
    "🛩️": "heroicons:paper-airplane",
    "🛫": "heroicons:paper-airplane",
    "🛬": "heroicons:paper-airplane",
    "🚁": "material-symbols:helicopter",
    "🚂": "material-symbols:train",
    "🚆": "material-symbols:train",
    "🚄": "material-symbols:train",
    "🚅": "material-symbols:train",
    "🚈": "material-symbols:train",
    "🚝": "material-symbols:train",
    "🚞": "material-symbols:train",
    "🚋": "material-symbols:tram",
    "🚃": "material-symbols:train",
    "🚟": "material-symbols:train",
    "🚠": "material-symbols:cable-car",
    "🚡": "material-symbols:cable-car",
    "⛵": "material-symbols:sailing",
    "🛶": "material-symbols:kayaking",
    "🚤": "material-symbols:directions-boat",
    "🛥️": "material-symbols:directions-boat",
    "🚢": "material-symbols:directions-boat",

    // Science & Nature
    "🔬": "material-symbols:science",
    "🧪": "material-symbols:science",
    "🧬": "material-symbols:biotech",
    "💉": "material-symbols:vaccines",
    "💊": "material-symbols:medication",
    "🩺": "heroicons:heart",
    "🌡️": "heroicons:fire",
    "🔭": "material-symbols:telescope",
    "🗿": "material-symbols:landscape",
    "⚗️": "material-symbols:science",
    "🧫": "material-symbols:science",
    "🧲": "material-symbols:magnet-on",

    // Weather & Nature
    "☀️": "heroicons:sun",
    "🌤️": "material-symbols:partly-cloudy-day",
    "⛅": "material-symbols:cloud",
    "🌥️": "material-symbols:cloud",
    "☁️": "heroicons:cloud",
    "🌦️": "material-symbols:rainy",
    "🌧️": "material-symbols:rainy",
    "⛈️": "material-symbols:thunderstorm",
    "🌩️": "material-symbols:thunderstorm",
    "🌨️": "material-symbols:weather-snowy",
    "❄️": "material-symbols:ac-unit",
    "☃️": "material-symbols:ac-unit",
    "⛄": "material-symbols:ac-unit",
    "🌬️": "material-symbols:air",
    "💨": "material-symbols:air",
    "🌪️": "material-symbols:tornado",
    "🌫️": "material-symbols:foggy",
    "🌊": "heroicons:lifebuoy",
    "💧": "material-symbols:water-drop",
    "💦": "material-symbols:water-drop",

    // Sports & Activities
    "⚽": "material-symbols:sports-soccer",
    "🏀": "material-symbols:sports-basketball",
    "🏈": "material-symbols:sports-football",
    "⚾": "material-symbols:sports-baseball",
    "🎾": "material-symbols:sports-tennis",
    "🏐": "material-symbols:sports-volleyball",
    "🏉": "material-symbols:sports-rugby",
    "🥎": "material-symbols:sports-baseball",
    "🏓": "material-symbols:sports-tennis",
    "🏸": "material-symbols:sports-tennis",
    "🥅": "material-symbols:sports-soccer",
    "🏑": "material-symbols:sports-hockey",
    "🏒": "material-symbols:sports-hockey",
    "🥍": "material-symbols:sports-tennis",
    "🏏": "heroicons:trophy",
    "🎱": "material-symbols:sports-esports",
    "🏆": "heroicons:trophy",
    "🥇": "heroicons:trophy",
    "🥈": "heroicons:trophy",
    "🥉": "heroicons:trophy",
    "🎖️": "heroicons:trophy",
    "🏅": "heroicons:trophy",
    "🎗️": "heroicons:trophy",

    // Time & Calendar
    "⏰": "heroicons:clock",
    "⏲️": "heroicons:clock",
    "⏱️": "heroicons:clock",
    "⏳": "heroicons:clock",
    "⌛": "heroicons:clock",

    // Additional unique emojis
    "🎯": "material-symbols:gps-fixed",
    "🎲": "material-symbols:casino",
    "🃏": "material-symbols:casino",
    "🀄": "material-symbols:casino",
    "🎴": "material-symbols:casino",
    "🎭": "material-symbols:theater-comedy",
    "🎪": "material-symbols:festival",
    "🎧": "material-symbols:headphones",
    "🎼": "heroicons:musical-note",
    "🎹": "material-symbols:piano",
    "🥁": "material-symbols:music-note",
    "🎷": "material-symbols:music-note",
    "🎺": "material-symbols:music-note",
    "🎸": "material-symbols:music-note",
    "🪕": "material-symbols:music-note",
    "🎻": "material-symbols:music-note"
  };

  // Derive the iconify icon name from the emoji
  let iconName = $derived(() => {
    if (!emoji) return null;
    return EMOJI_TO_ICONIFY[emoji] || null;
  });
</script>

{#if iconName}
  <Icon icon={iconName} class={className} />
{:else if emoji}
  <span class={className}>{emoji}</span>
{/if} 